language: python
cache: pip
addons:
  postgresql: "9.6"
env:
- DATABASE_URL=postgresql://postgres:@127.0.0.1/family_tree
python:
- '3.6'
services:
- redis
before_script:
- createdb -U postgres -O postgres family_tree
before_install:
- pip install --upgrade pip
- pip install --upgrade setuptools
install:
- pip install -r requirements.txt
script:
- ./manage.py test --settings=settings.test
- pycodestyle ./
