# Generated by Django 3.1.1 on 2020-09-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ancestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('birthplace', models.CharField(blank=True, max_length=100, verbose_name='Geboorteplaats')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Overlijdensdatum')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('firstname', models.CharField(blank=True, max_length=100, verbose_name='Voornaam')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Man'), ('f', 'Vrouw')], max_length=1)),
                ('lastname', models.CharField(blank=True, max_length=100, verbose_name='Achternaam')),
                ('middlename', models.CharField(blank=True, max_length=100, verbose_name='Tussenvoegsel')),
                ('place_of_death', models.CharField(blank=True, max_length=100, verbose_name='Plaats van overlijden')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_of_father', to='tree.ancestor', verbose_name='Vader')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_of_mother', to='tree.ancestor', verbose_name='Moeder')),
            ],
            options={
                'verbose_name': 'Voorouder',
                'verbose_name_plural': 'Voorouders',
                'ordering': ['birthdate'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_divorce', models.DateField(blank=True, null=True, verbose_name='Scheidingsdatum')),
                ('date_of_marriage', models.DateField(blank=True, null=True, verbose_name='Trouwdatum')),
                ('place_of_marriage', models.CharField(blank=True, max_length=100, verbose_name='Plaats van trouwen')),
                ('husband', models.ForeignKey(limit_choices_to=models.Q(gender='m'), on_delete=django.db.models.deletion.CASCADE, related_name='marriages_of_husband', to='tree.ancestor', verbose_name='Man')),
                ('wife', models.ForeignKey(limit_choices_to=models.Q(gender='f'), on_delete=django.db.models.deletion.CASCADE, related_name='marriages_of_wife', to='tree.ancestor', verbose_name='Vrouw')),
            ],
            options={
                'verbose_name': 'Huwelijk',
                'verbose_name_plural': 'Huwelijken',
                'ordering': ['date_of_marriage'],
            },
        ),
    ]
