# Generated by Django 3.1.1 on 2021-01-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20201209_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChristianName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meisjesnaam')),
                ('male_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jongensnaam')),
                ('name', models.CharField(blank=True, max_length=201, verbose_name='Naam')),
                ('name_type', models.CharField(choices=[('b', 'Jongens- en meisjesnaam'), ('f', 'Meisjesnaam'), ('m', 'Jongensnaam')], max_length=1, verbose_name='Soort naam')),
                ('alias_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='tree.christianname')),
            ],
            options={
                'verbose_name': 'Doopnaam',
                'verbose_name_plural': 'Doopnamen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ancestor',
            name='christian_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ancestors', to='tree.christianname', verbose_name='Doopnaam'),
        ),
        migrations.AddConstraint(
            model_name='christianname',
            constraint=models.UniqueConstraint(condition=models.Q(('female_name__isnull', False), ('male_name__isnull', False), ('name_type', 'b')), fields=('name_type', 'female_name', 'male_name'), name="Unique constraint for boy's and girl's name"),
        ),
        migrations.AddConstraint(
            model_name='christianname',
            constraint=models.UniqueConstraint(condition=models.Q(('female_name__isnull', False), ('male_name__isnull', True), ('name_type', 'f')), fields=('name_type', 'female_name', 'male_name'), name="Unique constraint for girl's name"),
        ),
        migrations.AddConstraint(
            model_name='christianname',
            constraint=models.UniqueConstraint(condition=models.Q(('female_name__isnull', True), ('male_name__isnull', False), ('name_type', 'm')), fields=('name_type', 'female_name', 'male_name'), name="Unique constraint for boy's name"),
        ),
    ]
