# Generated by Django 3.1.1 on 2021-01-19 21:40

from django.db import migrations


def set_christian_names(apps, schema_editor):
    Ancestor = apps.get_model('tree', 'Ancestor')
    ChristianName = apps.get_model('tree', 'ChristianName')
    christian_names = {}
    for ancestor in Ancestor.objects.exclude(firstname='').all():
        if ancestor.gender == 'f':
            key = ('f', ancestor.firstname, None)
            christian_name = christian_names.get(key)
            if not christian_name:
                christian_name = ChristianName(
                    name_type='f',
                    female_name=ancestor.firstname
                )
                christian_name.save()
                ancestor.christian_name = christian_name
                ancestor.save()
            christian_names[key] = christian_name
        elif ancestor.gender == 'm':
            key = ('m', ancestor.firstname, None)
            christian_name = christian_names.get(key)
            if not christian_name:
                christian_name = ChristianName(
                    name_type='m',
                    male_name=ancestor.firstname
                )
                christian_name.save()
                ancestor.christian_name = christian_name
                ancestor.save()
            christian_names[key] = christian_name


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20210119_2138'),
    ]

    operations = [
        migrations.RunPython(set_christian_names, migrations.RunPython.noop)
    ]
