# Generated by Django 3.1.1 on 2021-01-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20210119_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ancestor',
            name='firstname',
        ),
    ]
