# Generated by Django 3.1.1 on 2021-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20210205_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biolink',
            name='url',
            field=models.URLField(unique=True, verbose_name='Url'),
        ),
        migrations.AddIndex(
            model_name='ancestor',
            index=models.Index(fields=['middlename', 'lastname'], name='tree_ancest_middlen_94f5c2_idx'),
        ),
    ]
